# Generated by Django 5.2.6 on 2026-04-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_requests', models.PositiveIntegerField(default=50, help_text='Number of requests allowed')),
                ('window_hours', models.PositiveIntegerField(default=1, help_text='Time window in hours')),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable rate limiting')),
            ],
            options={
                'verbose_name': 'Rate Limit Setting',
                'verbose_name_plural': 'Rate Limit Settings',
            },
        ),
    ]
